"""Losslessly encode the frozen HB-1 direction nodes in 32 bits instead of 64."""
from pathlib import Path
import hashlib
import json
import re
import shutil
import struct
import zipfile

ROOT=Path(__file__).resolve().parents[2]
MAIN=ROOT.parent/'UNSW-Battlecode-2026'
src=ROOT/'bots/kenma-03-pocket-queen'
dst=ROOT/'bots/kenma-08-lossless-direction'
assert not dst.exists(), 'Never overwrite a snapshot'
s=(src/'hb1_direction_compact.hpp').read_text()
prefix,body=s.split('inline constexpr unsigned long long dirc_nodes[] = {',1)
words=[int(x,16) for x in re.findall(r'0x[0-9a-fA-F]+',body)]
thresholds=sorted({w&0xffffffff for w in words if ((w>>32)&0x7fff)!=0x7fff})
assert len(thresholds)<=4096
lookup={v:i for i,v in enumerate(thresholds)}
packed=[]
for w in words:
    f=(w>>32)&0x7fff
    value=w&0xffffffff
    if f==0x7fff:
        assert not value&(1<<30), 'Leaf collides with branch marker'
        assert abs(struct.unpack('<f',struct.pack('<I',value))[0])<2
        p=value
        restored=(0x7fff<<32)|p
    else:
        right=w>>48; missing=(w>>47)&1
        assert 0<=f<512 and 0<right<512
        p=f|(right<<9)|(lookup[value]<<18)|(1<<30)|(missing<<31)
        restored=((p&511)<<32)|(((p>>9)&511)<<48)|(((p>>31)&1)<<47)|thresholds[(p>>18)&4095]
    assert restored==w, 'Node encoding must be bit-exact'
    packed.append(p)
shutil.copytree(src,dst,ignore=shutil.ignore_patterns('.unswbc-build','__pycache__'))
def array(name,values):
    return 'inline constexpr unsigned int '+name+'[] = {\n'+''.join(','.join(f'0x{v:08x}u' for v in values[i:i+12])+',\n' for i in range(0,len(values),12))+'};\n'
prefix=prefix[prefix.index('#pragma once'):]
new='// Generated by tools/kenma/compact_direction.py; bit-exact HB-1 node values.\n'+prefix
new+='static_assert(sizeof(unsigned int)==4);\n'+array('dirc_thresholds',thresholds)+array('dirc_nodes',packed)+'} // namespace hb1\n'
(dst/'hb1_direction_compact.hpp').write_text(new)
p=dst/'hb1_compact.hpp';e=p.read_text()
e=e.replace('// HB-1 hb1-04: evaluator for the 8-byte preorder direction model in hb1_direction_compact.hpp.','// Kenma 08: exact 4-byte preorder nodes; branch thresholds are shared without rounding.')
e=e.replace('unsigned long long const* nd','unsigned int const* nd').replace('unsigned long long w = nd[j];','unsigned int w = nd[j];')
e=e.replace('unsigned f = unsigned(w >> 32) & 0x7FFFu;\n            if (f == 0x7FFFu)', 'unsigned f = w & 511u;\n            if (!(w & (1u << 30)))')
e=e.replace('((w >> 47) & 1u) : (v < dirc_f32(w))','((w >> 31) & 1u) : (v < dirc_f32(dirc_thresholds[(w >> 18) & 4095u]))')
e=e.replace('int(w >> 48)','int((w >> 9) & 511u)')
p.write_text(e)
(dst/'README.md').write_text('''# Kenma 08 — lossless direction model storage

Parent: kenma-03-pocket-queen. All strategy and model predictions are intended to remain identical. Encodes each existing direction-model node in four bytes instead of eight: branch feature (9 bits), right offset (9), exact threshold table index (12), branch marker (1), missing direction (1). Leaves retain their complete float32 bit pattern; the branch marker bit is unused by every original leaf (all absolute leaf values are below 2).

The generator reconstructs and checks every original 64-bit node exactly. Thresholds and leaves are never rounded. This is a deployment-space and memory control, not a claimed playing-strength improvement. Generated by tools/kenma/compact_direction.py; report main build/kenma/lossless-direction/report.json. Native prediction parity and exact-source sandbox checks are required before adopting the representation in a stronger candidate.
''')
out=MAIN/'build/kenma/lossless-direction';out.mkdir(exist_ok=True)
with zipfile.ZipFile(out/f'{dst.name}.zip','w',zipfile.ZIP_DEFLATED) as z:
    for p in sorted(dst.iterdir()):
        if p.is_file() and (p.suffix in ('.cpp','.hpp','.h','.cc','.toml','.md') or p.name=='.gitignore'): z.write(p,p.name)
report=dict(parent=src.name,bot=dst.name,nodes=len(words),unique_thresholds=len(thresholds),reconstructed_nodes=len(words),old_model_bytes=len(words)*8,new_model_bytes=4*(len(words)+len(thresholds)),zip_bytes=(out/f'{dst.name}.zip').stat().st_size,source_model_sha256=hashlib.sha256(s.encode()).hexdigest())
(out/'report.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report),flush=True)
