OVERRIDE = {
    "v_dive": 3.0,
    "sprint3_saturated_limit": 4,
    "sprint3_late_from": 40,
    "sprint3_late_limit": 6,
    "sprint3_sparse_from": 150,
    "big_cap_late_from": 40,
    "big_cap_late": 48,
    "big_cap_mid_from": 40,
    "big_cap_mid_until": 150,
    "big_cap_mid": 64,
    "big_cap_sparse_from": 150,
    "big_cap_sparse_units": 20,
    "big_cap_sparse": 64,
    "sprint3_sparse_limit": 8,
    "flood_cap_late_from": 150,
    "flood_cap_long_late": 24,
    "flood_cap_long_sparse": 32,
}
