"""Fit and export Loki's observation-safe gradient-boosted action ranker.

Run with the project interpreter:
  .venv/bin/python tools/loki/train.py --replays /path/to/374088.replay ...

Training dependency: scikit-learn (installed in the project's .venv). The bot
uses the exported threshold trees in trained_model.py and has no ML dependency.
"""
import argparse
from collections import Counter, defaultdict
import hashlib
import json
import math
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
BOT = ROOT / "bots" / "loki-v01-teacher-ranker"
ARTIFACT = ROOT / "experiment_data" / "loki-v01-teacher-ranker"
sys.path.insert(0, str(ROOT / "tools" / "loki"))
from replay_data import extract_game
from loki_features import FEATURE_NAMES


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def action_name(action):
    return "split" if action[0] == "split" else "move" + str(len(action[1]))


def as_matrix(groups):
    x, y, weights = [], [], []
    for group in groups:
        n = len(group["features"])
        if n < 2:
            continue
        negative_weight = 0.5 / (n - 1)
        for i, row in enumerate(group["features"]):
            x.append(row)
            chosen = i == group["label"]
            y.append(1 if chosen else 0)
            weights.append(group["sample_weight"] * (0.5 if chosen else negative_weight))
    return x, y, weights


def train_model(groups, *, estimators=48, depth=2, leaf=100, seed=7771):
    from sklearn.ensemble import GradientBoostingClassifier

    x, y, weights = as_matrix(groups)
    if not x or len(set(y)) != 2:
        raise ValueError("Need positive and negative candidate rows to fit Loki")
    model = GradientBoostingClassifier(
        loss="log_loss",
        learning_rate=0.05,
        n_estimators=estimators,
        max_depth=depth,
        min_samples_leaf=leaf,
        subsample=0.8,
        random_state=seed,
    )
    model.fit(x, y, sample_weight=weights)
    return model


def score_group(model, group):
    return model.decision_function(group["features"])


def ranking_metrics(model, groups):
    seen = evaluated = correct = 0
    split_seen = split_correct = 0
    per_game = defaultdict(lambda: [0, 0])
    for group in groups:
        if not group.get("features"):
            continue
        scores = score_group(model, group)
        chosen = max(range(len(scores)), key=scores.__getitem__)
        match = chosen == group["label"]
        evaluated += 1
        correct += match
        per_game[group["game"]][0] += int(match)
        per_game[group["game"]][1] += 1
        if group["action"][0] == "split":
            split_seen += 1
            split_correct += int(match)
    return {
        "groups": evaluated,
        "top1_accuracy": correct / max(1, evaluated),
        "split_groups": split_seen,
        "split_top1_accuracy": split_correct / max(1, split_seen),
        "by_game": {
            game: {"groups": values[1], "top1_accuracy": values[0] / max(1, values[1])}
            for game, values in sorted(per_game.items())
        },
    }


def export_tree(tree):
    t = tree.tree_
    nodes = []
    for i in range(t.node_count):
        left, right = int(t.children_left[i]), int(t.children_right[i])
        if left == right:
            nodes.append([-1, 0.0, -1, -1, float(t.value[i][0][0])])
        else:
            nodes.append([
                int(t.feature[i]), float(t.threshold[i]), left, right, 0.0
            ])
    return nodes


def export_model(model, path, source_hashes):
    prior = model.init_.class_prior_
    bias = math.log(float(prior[1]) / float(prior[0]))
    trees = [export_tree(estimator[0]) for estimator in model.estimators_]
    data = {
        "bias": bias,
        "learning_rate": float(model.learning_rate),
        "feature_names": list(FEATURE_NAMES),
        "source_hashes": source_hashes,
        "trees": trees,
    }
    # Confirm that exported inference reproduces sklearn's raw ranking scores.
    sample = [[0.0] * len(FEATURE_NAMES), [0.5] * len(FEATURE_NAMES)]
    expected = model.decision_function(sample)
    got = [raw_export_score(row, data) for row in sample]
    if max(abs(float(a) - b) for a, b in zip(expected, got)) > 1e-6:
        raise AssertionError("Exported tree score differs from the fitted estimator")
    path.write_text(
        '"""Generated by tools/loki/train.py; standard-library inference only."""\n'
        "MODEL = " + repr(data) + "\n"
    )
    return data


def raw_export_score(vector, data):
    score = data["bias"]
    for tree in data["trees"]:
        node = 0
        while tree[node][0] >= 0:
            feature, threshold, left, right, _value = tree[node]
            node = left if vector[feature] <= threshold else right
        score += data["learning_rate"] * tree[node][4]
    return score


def collect(paths, side, keep_every):
    groups, stats, manifest = [], {}, []
    for path in paths:
        path = Path(path).resolve()
        game_stats = Counter()
        for item in extract_game(path, teacher_side=side, keep_every=keep_every):
            if "_summary" in item:
                game_stats.update(item["_summary"])
            else:
                groups.append(item)
        stats[path.stem] = dict(game_stats)
        manifest.append({
            "game_id": path.stem,
            "path": str(path),
            "visualiser_url": f"https://game.battlecode.au/visualiser?match={path.stem}",
            "sha256": sha256(path),
        })
        print(f"loaded {path.stem}: {dict(game_stats)}", flush=True)
    return groups, stats, manifest


def choose_top1_baseline(groups):
    # Uniform random over the exact candidate menu is the honest reference for
    # a replay behavior-cloning score; report both its expected accuracy and
    # the learned model's candidate count distribution.
    return {
        "uniform_expected_top1": sum(1 / len(g["features"]) for g in groups if g["features"])
        / max(1, sum(bool(g["features"]) for g in groups)),
        "mean_candidates": sum(len(g["features"]) for g in groups)
        / max(1, len(groups)),
    }


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--replays", nargs="+", required=True)
    ap.add_argument("--teacher-submission", default="7771")
    ap.add_argument("--teacher-side", choices=("A", "B"), default="A")
    ap.add_argument("--keep-every", type=int, default=5)
    ap.add_argument("--estimators", type=int, default=48)
    ap.add_argument("--depth", type=int, default=2)
    ap.add_argument("--leaf", type=int, default=100)
    ap.add_argument("--out", type=Path, default=ARTIFACT)
    ap.add_argument("--model-out", type=Path, default=BOT / "trained_model.py")
    args = ap.parse_args()
    if args.keep_every < 1:
        ap.error("--keep-every must be positive")
    paths = sorted((Path(p) for p in args.replays), key=lambda p: p.stem)
    groups, game_stats, replay_manifest = collect(paths, args.teacher_side, args.keep_every)
    if not groups:
        raise SystemExit("No matched teacher actions fit Bifröst v01's candidate menu")

    series = defaultdict(list)
    for group in groups:
        series[group["series"]].append(group)
    validation = {}
    known_series = sorted(name for name in series if name != "other")
    if len(known_series) >= 2:
        for held_out in known_series:
            training = [g for g in groups if g["series"] != held_out]
            holdout = series[held_out]
            cv = train_model(
                training, estimators=args.estimators, depth=args.depth, leaf=args.leaf
            )
            validation[held_out] = {
                **ranking_metrics(cv, holdout),
                "uniform_reference": choose_top1_baseline(holdout),
                "train_groups": len(training),
            }
            print(f"held-out {held_out}: {validation[held_out]}", flush=True)

    model = train_model(
        groups, estimators=args.estimators, depth=args.depth, leaf=args.leaf
    )
    hashes = {entry["game_id"]: entry["sha256"] for entry in replay_manifest}
    export_model(model, args.model_out, hashes)
    training_summary = {
        "teacher_submission": args.teacher_submission,
        "teacher_side": args.teacher_side,
        "training_groups": len(groups),
        "actions_by_type": dict(Counter(action_name(g["action"]) for g in groups)),
        "candidate_count": {
            "mean": sum(len(g["features"]) for g in groups) / len(groups),
            "min": min(len(g["features"]) for g in groups),
            "max": max(len(g["features"]) for g in groups),
        },
        "in_sample": ranking_metrics(model, groups),
        "uniform_reference": choose_top1_baseline(groups),
        "held_out_by_series": validation,
        "replay_stats": game_stats,
        "replays": replay_manifest,
        "features": list(FEATURE_NAMES),
        "model": {
            "kind": "gradient_boosted_candidate_classifier",
            "estimators": args.estimators,
            "max_depth": args.depth,
            "min_samples_leaf": args.leaf,
            "learning_rate": model.learning_rate,
            "train_sample_every": args.keep_every,
        },
    }
    write_json(args.out / "training_summary.json", training_summary)
    write_json(args.out / "replay_manifest.json", {
        "team": "龙虎豹",
        "teacher_submission": args.teacher_submission,
        "series": {
            "ranked-vs-calc": [p.stem for p in paths if p.stem.startswith("374")],
            "ranked-vs-shink-ai-6500": [p.stem for p in paths if p.stem.startswith("375")],
        },
        "side": args.teacher_side,
        "replays": replay_manifest,
    })
    print(f"exported {args.model_out}; summary {args.out / 'training_summary.json'}")


if __name__ == "__main__":
    main()

