#!/usr/bin/env python3
"""Generate atlas.hpp (terrain + bed classes of the public maps) from map files, in the format of
tools/cx/build_atlas.py as found in carthage-05's atlas.hpp.

    python3 tools/bokuto/build_atlas.py maps/live/*.map > atlas.hpp
"""
import math, sys
from pathlib import Path


def parse(path):
    W = H = 0; tiles = {}; edges = {}; name = Path(path).stem
    for ln in Path(path).read_text().splitlines():
        p = ln.split()
        if not p: continue
        if p[0] == 'MAP': W, H = int(p[1]), int(p[2])
        elif p[0] == 'TILE': tiles[(int(p[1]), int(p[2]))] = (int(p[3]), int(p[4]))
        elif p[0] == 'EDGE':
            idx, kind, pid = int(p[1]), int(p[2]), int(p[3])
            col, row = idx % (W + 1), idx // (W + 1)
            if col >= W or row >= 2 * H: continue
            edges[(row % 2, col, row // 2)] = (kind, pid)
    NC = W * H
    ek = ['.'] * (2 * NC); portals = []
    for (ori, x, y), (kind, pid) in edges.items():
        k = (y * W + x) if ori == 0 else NC + y * W + x
        ek[k] = '.' if kind == 0 else 'w' if kind == 1 else 'p'
        if kind == 2: portals.append((k, pid))
    beds = ['0'] * NC
    for (x, y), (mn, mx) in tiles.items():
        if mx > 0:
            mean = (mn + mx) / 2.0
            beds[y * W + x] = str(min(9, int(round(math.log2(mean))) + 1)) if mean >= 1 else '1'
    portals.sort()
    return name, W, H, ''.join(ek), portals, ''.join(beds)


def chunks(s, n=200):
    return [s[i:i + n] for i in range(0, len(s), n)]


def main(paths):
    maps = [parse(p) for p in paths]
    out = ['// generated by tools/bokuto/build_atlas.py from maps/live/*.map -- do not edit', '#pragma once', '',
           'namespace ares::atlas {', '', 'struct Map {', '    int W, H;', '    const char* name;',
           '    const char* edges;   // 2*W*H: \'.\' open, \'w\' kelp, \'p\' portal',
           '    const int* portals;  // edge_key, id, edge_key, id, ...', '    int n_portals;',
           '    const char* beds;    // W*H: \'0\' none, else bed class', '};', '']
    for i, (name, W, H, ek, portals, beds) in enumerate(maps):
        flat = ', '.join(f'{k}, {pid}' for k, pid in portals) or '0'
        out.append(f'inline const int portals_{i}[] = {{{flat}}};')
        out.append(f'inline const char edges_{i}[] =')
        out += [f'        "{c}"' for c in chunks(ek)]
        out[-1] += ';'
        out.append(f'inline const char beds_{i}[] =')
        out += [f'        "{c}"' for c in chunks(beds)]
        out[-1] += ';'
        out.append('')
    out.append('inline const Map maps[] = {')
    for i, (name, W, H, ek, portals, beds) in enumerate(maps):
        out.append(f'    {{{W}, {H}, "{name}", edges_{i}, portals_{i}, {len(portals)}, beds_{i}}},')
    out.append('};')
    out.append(f'inline constexpr int n_maps = {len(maps)};')
    out.append('')
    out.append('}  // namespace ares::atlas')
    print('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1:])
