"""Atlas modules for ouroboros-s02 bots: terrain + pearl beds of the ten public maps.

    python3 tools/ouros2/build_atlas2.py bots/<bot> [maps ...]

Adapted from tools/chaewon/build_atlas.py (chaewon lineage): same edge encoding
(k < NC north side of cell k, k >= NC west side of cell k-NC; '.' open, 'w'
kelp, 'p' portal) and first-view matching in the bot.  Adds the exact respawn
gap classes: MAPS = [(name, start_len, edges, portals, beds, classes)] with
beds a W*H string ('0' no bed, chr(49 + i) = gap class i) and classes a tuple
of (min_gap, max_gap).  Terrain and bed geometry are static map facts; pearls
and countdowns are still learnt by sight.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "tools" / "ouroboros"))
from mapview import load_map  # noqa: E402

LIVE10 = ["schooltime", "portals", "slithery_fight", "queen_of_spades", "default", "trophy",
          "dilemma", "autarky", "devil", "trauma"]


def build(name):
    m = load_map((REPO / "maps" / (name + ".map")).read_text())
    W, H = m["W"], m["H"]
    NC = W * H
    e = bytearray(b"." * (2 * NC))
    portals = []
    for (x, y) in m["kelp_h"]:
        e[y * W + x] = ord("w")
    for (x, y) in m["kelp_v"]:
        e[NC + y * W + x] = ord("w")
    for (x, y), pid in m["portal_h"].items():
        e[y * W + x] = ord("p")
        portals.append((y * W + x, pid))
    for (x, y), pid in m["portal_v"].items():
        e[NC + y * W + x] = ord("p")
        portals.append((NC + y * W + x, pid))
    classes = []
    beds = bytearray(b"0" * NC)
    for (x, y), t in m["tiles"].items():
        if t[1] > 0:
            k = (t[0], t[1])
            if k not in classes:
                classes.append(k)
            beds[y * W + x] = 49 + classes.index(k)
    start_len = len(m["dragons"][0][1])
    return (W, H), (name, start_len, e.decode(), tuple(sorted(portals)), beds.decode(), tuple(classes))


def main():
    out = Path(sys.argv[1])
    names = sys.argv[2:] or LIVE10
    by = {}
    for n in names:
        dims, rec = build(n)
        by.setdefault(dims, []).append(rec)
    for (W, H), recs in by.items():
        p = out / ("atlas_%dx%d.py" % (W, H))
        p.write_text("# generated by tools/ouros2/build_atlas2.py from maps/*.map\nMAPS = %r\n" % (recs,))
        print(p, [r[0] for r in recs])


if __name__ == "__main__":
    main()
