OVERRIDE = {
    "v_dive": 3.0,
    "opening_density_radius": 9,
    "opening_density_len_cap": 6,
    "opening_density_floor": 2,
    "opening_density_per": 2.0,
    "opening_density_cap": 8.0,
    "opening_bed_horizon": 20,
    "split_open_until": 80,
    "split_open_bonus": 4.0,
    "r_unseen": 0.15,
    "frontier_search_depth": 4,
    "sprint3_saturated_limit": 4,
    "sprint3_late_from": 150,
    "sprint3_late_limit": 5,
    "big_cap_late_from": 40,
    "big_cap_late": 48,
    "big_cap_sparse_from": 150,
    "big_cap_sparse_units": 20,
    "big_cap_sparse": 64,
    "sprint3_sparse_limit": 8,
    "flood_cap_late_from": 150,
    "flood_cap_long_late": 24,
    "flood_cap_long_sparse": 32,
}
