"""HB-1 Q4 (hb1-04): re-encode the direction blob (direction_v03.bin) as 8-byte nodes in a C++ header that fits the
judge's 48 MiB per-process wasm memory (unswbc sandbox.MAX_MEMORY_PAGES = 768).

    .venv/bin/python tools/hb1/q4_compact_direction.py BOTDIR

Node word (uint64): bits 0-31 float32 (threshold, or leaf value); bits 32-46 feature index (0x7FFF = leaf);
bit 47 missing-goes-left; bits 48-63 right-child offset from this node. Nodes are stored in depth-first preorder so
the left child is always the next node. Exact: same thresholds, leaves and routing as the blob.
Writes BOTDIR/hb1_direction_compact.hpp.
"""
import struct, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
NODE = np.dtype([('f', '<i2'), ('t', '<f4'), ('yes', '<i4'), ('no', '<i4'), ('miss', '<i4'), ('leaf', '<f4')], align=True)


def read_blob(path):
    b = Path(path).read_bytes()
    assert b[:4] == b'HB1D'
    off = 4
    K, n_feat, n_trees, n_nodes, n_classes = struct.unpack_from('<5i', b, off); off += 20
    base = struct.unpack_from(f'<{K}f', b, off); off += 4 * K
    classes = struct.unpack_from(f'<{n_classes}i', b, off); off += 4 * n_classes
    (ln,) = struct.unpack_from('<i', b, off); off += 4
    names = b[off:off + ln].decode().split('\n'); off += ln
    off = (off + 7) & ~7
    starts = np.frombuffer(b, '<i4', n_trees, off); off += 4 * n_trees
    off = (off + 7) & ~7
    nodes = np.frombuffer(b, NODE, n_nodes, off)
    return K, names, list(base), list(classes), starts, nodes


def encode_tree(nd):
    """nd: structured array of one tree (node 0 = root). -> list of uint64 in preorder."""
    out = []

    def emit(i):
        pos = len(out)
        out.append(0)
        if nd['f'][i] < 0:
            out[pos] = (0x7FFF << 32) | struct.unpack('<I', struct.pack('<f', float(nd['leaf'][i])))[0]
            return
        emit(int(nd['yes'][i]))
        right = len(out) - pos
        assert right < 65536
        emit(int(nd['no'][i]))
        f = int(nd['f'][i])
        assert f < 0x7FFF
        miss_left = int(nd['miss'][i] == nd['yes'][i])
        out[pos] = (right << 48) | (miss_left << 47) | (f << 32) | struct.unpack('<I', struct.pack('<f', float(nd['t'][i])))[0]
    emit(0)
    return out


def main(botdir):
    K, names, base, classes, starts, nodes = read_blob(ROOT / 'build/hb1/export/direction_v03.bin')
    words, tstart = [], []
    ends = list(starts[1:]) + [len(nodes)]
    for s, e in zip(starts, ends):
        tstart.append(len(words))
        words += encode_tree(nodes[s:e])
    F = lambda x: repr(float(np.float32(x))) + 'f'
    L = ['// generated by tools/hb1/q4_compact_direction.py - do not edit.',
         '// HB-1 hb1-04: the hb1-03 direction GBT (0.854 held-out) as 8-byte preorder nodes; see the generator for the',
         '// word layout. Exactly the same routing and leaves as build/hb1/export/direction_v03.bin.',
         '#pragma once', 'namespace hb1 {',
         f'inline constexpr int dirc_K = {K};', f'inline constexpr int dirc_n_trees = {len(tstart)};',
         f'inline constexpr int dirc_n_feat = {len(names)};',
         'inline constexpr float dirc_base[] = {' + ', '.join(F(x) for x in base) + '};',
         'inline constexpr int dirc_classes[] = {' + ', '.join(map(str, classes)) + '};',
         'inline constexpr char const* dirc_feats[] = {' + ', '.join(f'"{n}"' for n in names) + '};',
         'inline constexpr int dirc_tree_start[] = {' + ','.join(map(str, tstart)) + '};',
         'inline constexpr unsigned long long dirc_nodes[] = {']
    for i in range(0, len(words), 12):
        L.append(','.join(f'0x{w:x}' for w in words[i:i + 12]) + ',')
    L += ['};', '}  // namespace hb1', '']
    out = Path(botdir) / 'hb1_direction_compact.hpp'
    out.write_text('\n'.join(L))
    print(f'{len(tstart)} trees, {len(words)} nodes, {len(words) * 8 / 1e6:.1f} MB of nodes, header '
          f'{out.stat().st_size / 1e6:.1f} MB -> {out}')


if __name__ == '__main__':
    main(sys.argv[1])
