"""Policy and feature parameters for the Python Hunter V22 port."""

EWMA_ALPHA = 0.25
MIN_ATTACK_UNITS = 3
SPLIT_STOP = 220
CROWN_START = 220

LOCAL_SAFETY_CAP = 24
SAFETY_REACHABLE_WEIGHT = 1
SAFETY_EXIT_WEIGHT = 8
SAFETY_ENEMY_WEIGHT = 12
SAFETY_DEAD_END_PENALTY = 20
