#!/usr/bin/env python3
"""Build atlas.hpp (terrain of the ten public maps) for a cx/anna C++ bot.

    python3 tools/cx/build_atlas.py bots/<bot> [maps ...]

Same source and edge-key convention as tools/chaewon/build_atlas.py (k < NC:
north side of cell k; k >= NC: west side of cell k - NC), via
tools/ouroboros/mapview.load_map. Per map: W, H, name, an edge string of 2*W*H
chars ('.' open, 'w' kelp, 'p' portal), portal (edge_key, id) pairs, and a bed
string of W*H chars ('0' none, else '1' + log2 class of the mean respawn gap,
capped at 'z'). The bot loads a map only if every edge of its first 7x7 view
agrees and exactly one map matches (World::atlas_try).
"""
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "tools" / "ouroboros"))
from mapview import load_map  # noqa: E402

LIVE10 = ["schooltime", "portals", "slithery_fight", "queen_of_spades", "default", "trophy",
          "dilemma", "autarky", "devil", "trauma"]


def build(name):
    m = load_map((REPO / "maps" / (name + ".map")).read_text())
    W, H = m["W"], m["H"]
    NC = W * H
    e = bytearray(b"." * (2 * NC))
    portals = []
    for (x, y) in m["kelp_h"]:
        e[y * W + x] = ord("w")
    for (x, y) in m["kelp_v"]:
        e[NC + y * W + x] = ord("w")
    for (x, y), pid in m["portal_h"].items():
        e[y * W + x] = ord("p")
        portals.append((y * W + x, pid))
    for (x, y), pid in m["portal_v"].items():
        e[NC + y * W + x] = ord("p")
        portals.append((NC + y * W + x, pid))
    beds = bytearray(b"0" * NC)
    for (x, y), t in m["tiles"].items():
        if t[1] > 0:
            mean = (t[0] + t[1]) / 2.0
            b = 1 + int(round(math.log2(max(1.0, mean))))
            beds[y * W + x] = 48 + min(b, 74)
    return W, H, name, e.decode(), sorted(portals), beds.decode()


def chunks(s, n=200):
    return "\n".join('        "%s"' % s[i:i + n] for i in range(0, len(s), n))


def main():
    out = Path(sys.argv[1]) / "atlas.hpp"
    names = sys.argv[2:] or LIVE10
    recs = [build(n) for n in names]
    parts = ["// generated by tools/cx/build_atlas.py from maps/*.map -- do not edit",
             "#pragma once", "", "namespace anna::atlas {", "",
             "struct Map {", "    int W, H;", "    const char* name;",
             "    const char* edges;   // 2*W*H: '.' open, 'w' kelp, 'p' portal",
             "    const int* portals;  // edge_key, id, edge_key, id, ...",
             "    int n_portals;", "    const char* beds;    // W*H: '0' none, else bed class",
             "};", ""]
    for i, (W, H, name, e, portals, beds) in enumerate(recs):
        flat = ", ".join("%d, %d" % kp for kp in portals) or "0"
        parts.append(f"inline const int portals_{i}[] = {{{flat}}};")
        parts.append(f"inline const char edges_{i}[] =\n{chunks(e)};")
        parts.append(f"inline const char beds_{i}[] =\n{chunks(beds)};")
    parts.append("")
    parts.append("inline const Map maps[] = {")
    for i, (W, H, name, e, portals, beds) in enumerate(recs):
        parts.append(f'    {{{W}, {H}, "{name}", edges_{i}, portals_{i}, {len(portals)}, beds_{i}}},')
    parts.append("};")
    parts.append(f"inline constexpr int n_maps = {len(recs)};")
    parts.append("")
    parts.append("}  // namespace anna::atlas")
    out.write_text("\n".join(parts) + "\n")
    print(out, [r[2] for r in recs], out.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
