"""Build atlas modules (full terrain of the public maps) for a chaewon bot.

    python3 tools/chaewon/build_atlas.py bots/chaewon-s02-atlas [maps ...]

Writes one module per map size, atlas_<W>x<H>.py, holding
MAPS = [(name, start_len, edges, portals, beds), ...] where
  edges   : str of 2*W*H chars in the bot's edge-key order (k < NC: north side
            of cell k; k >= NC: west side of cell k-NC): '.' open, 'w' kelp,
            'p' portal
  portals : tuple of (edge_key, portal_id)
  beds    : str of W*H chars: '0' no bed, else chr(48 + b) with
            b = 1 + round(log2(mean respawn gap)), mean gap = (min + max) / 2
The bot loads a candidate only if every edge in its first 7x7 view agrees.
"""
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "tools" / "ouroboros"))
from mapview import load_map  # noqa: E402

LIVE10 = ["schooltime", "portals", "slithery_fight", "queen_of_spades", "default", "trophy",
          "dilemma", "autarky", "devil", "trauma"]


def build(name):
    m = load_map((REPO / "maps" / (name + ".map")).read_text())
    W, H = m["W"], m["H"]
    NC = W * H
    e = bytearray(b"." * (2 * NC))
    portals = []
    for (x, y) in m["kelp_h"]:
        e[y * W + x] = ord("w")
    for (x, y) in m["kelp_v"]:
        e[NC + y * W + x] = ord("w")
    for (x, y), pid in m["portal_h"].items():
        e[y * W + x] = ord("p")
        portals.append((y * W + x, pid))
    for (x, y), pid in m["portal_v"].items():
        e[NC + y * W + x] = ord("p")
        portals.append((NC + y * W + x, pid))
    beds = bytearray(b"0" * NC)
    for (x, y), t in m["tiles"].items():
        if t[1] > 0:
            mean = (t[0] + t[1]) / 2.0
            b = 1 + int(round(math.log2(max(1.0, mean))))
            beds[y * W + x] = 48 + min(b, 40)
    start_len = len(m["dragons"][0][1])
    return (W, H), (name, start_len, e.decode(), tuple(sorted(portals)), beds.decode())


def main():
    out = Path(sys.argv[1])
    names = sys.argv[2:] or LIVE10
    by = {}
    for n in names:
        dims, rec = build(n)
        by.setdefault(dims, []).append(rec)
    for (W, H), recs in by.items():
        p = out / ("atlas_%dx%d.py" % (W, H))
        p.write_text("# generated by tools/chaewon/build_atlas.py from maps/*.map\nMAPS = %r\n" % (recs,))
        print(p, [r[0] for r in recs])


if __name__ == "__main__":
    main()
