from pathlib import Path
import json,hashlib
import pandas as pd,numpy as np
R=Path('/Users/alik/Documents/Projects/UNSW-Battlecode-2026');O=Path('/tmp/tanaka-r8');O.mkdir(exist_ok=True);out=json.loads((O/'audit.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
tp=R/'build/learn/kageyama/teachers_v1.parquet';sp=R/'build/learn/splits/games_split_v2.parquet';cp=R/'build/learn/kageyama/r2_confirm_cohort_v1.parquet';cv=R/'build/learn/kageyama/r2_confirm_coverage_v1.jsonl'
t=pd.read_parquet(tp,columns=['team','series_key']);d=pd.read_parquet(sp,columns=['game','map','series_key','split','map_era','ranked','in_scope','team_a','team_b']);c=pd.read_parquet(cp,columns=['game','map','series_key','teacher_sides','consumed_by','on_disk']);cov=pd.read_json(cv,lines=True,dtype={'game':str,'series_key':str});teams=set(t.team.astype(str));ts=set(t.series_key.astype(str));h=d[(d.split=='heldout_map')&(d.map_era=='post-m2')&d.ranked&d.in_scope&(d.team_a.astype(str).isin(teams)|d.team_b.astype(str).isin(teams))];h=h[~h.series_key.astype(str).isin(ts)]
x={'hashes':{p.name:sha(p) for p in [tp,sp,cp,cv]},'games':len(c),'series':int(c.series_key.nunique()),'maps':c.groupby('map').size().to_dict(),'exact_expected_set':set(c.game.astype(str))==set(h.game.astype(str)),'coverage_unique':not cov.game.duplicated().any(),'coverage_set_matches':set(cov.game)==set(c.game),'coverage_flags_true':int(cov.reproduced.sum()),'coverage_by_map':cov.groupby('map').reproduced.agg(['size','sum']).to_dict('index'),'teacher_processes':int(cov.teacher_processes.sum()),'teacher_sides':int(c.teacher_sides.str.split(',').str.len().sum()),'consumed_p2':int(c.consumed_by.str.contains('P-2',case=False).sum()),'on_disk':int(c.on_disk.sum()),'oracle_claim_scope':'Independent validation of stored flags and membership only; replay reproduction algorithm not rerun, no heldout action/winner labels projected.'}
assert x['exact_expected_set'] and x['coverage_set_matches'] and x['coverage_unique'] and x['coverage_flags_true']==115
out['r2_cohort']=x
# Enumerate all 4096 assignments to 12 fixed nonzero cluster IDs (not sorted by outcome), preserving bootstrap seed7.
from scipy.stats import binom
idx=np.random.default_rng(7).integers(0,51,(1000,51));counts=np.array([np.bincount(row,minlength=51)[:12] for row in idx]);bits=((np.arange(4096)[:,None]>>np.arange(12))&1);s=bits*2.5-2.;k=bits.sum(1);draw=s@counts.T/102;lower=np.percentile(draw,5,axis=1);point=s.sum(1)/102;sig=(binom.sf(k-1,12,.5)<=.075)&(point>0)&(lower>-.02);mass=.8**k*.2**(12-k)
out['ls_std']['mean_zero_asymmetric']['fixed_cluster_exact_enumeration']={'patterns':4096,'one_look_pass_probability':float(mass[sig].sum()),'accepted_patterns':int(sig.sum()),'accepted_by_positive_count':{str(a):int(sig[k==a].sum()) for a in range(13)},'scope':'12 fixed independent cluster IDs, each +.5 with p=.8 or -2 with p=.2;39 fixed zeros; denominator102pairs; full sign/point/bootstrap guards; seed7/1000linear'}
(O/'audit.json').write_text(json.dumps(out,indent=2));print(json.dumps({'cohort':x,'counterexample':out['ls_std']['mean_zero_asymmetric']['fixed_cluster_exact_enumeration']},indent=2))
